### ISSUE TITLE
Weirdness with properties and beforeEnd

### ISSUE THREAD

**Issue by ArseAssassin** [kefirjs/kefir#270]
I'm getting the following results using `beforeEnd`

```
> kefir.later(1).beforeEnd(() => 0).log()
[later.beforeEnd] <value> undefined
[later.beforeEnd] <value> 0
[later.beforeEnd] <end>
```

```
> kefir.constant(1).beforeEnd(() => 0).log()
[constant.beforeEnd] <value:current> 0
[constant.beforeEnd] <end:current>
```

To me it seems like the first example is working correctly while the second one eats the value of the property. I'd expect both of them to work the same.

**Comment by rpominov** [comment]
Hi, sorry for the slow response. This is because properties may have only a single _current_ value. The output could have been 
```
[constant.beforeEnd] <value:current> 1
[constant.beforeEnd] <value:current> 0
[constant.beforeEnd] <end:current>
```
but then we would have two _current_ values.

This is a bit controversial design decision, and we have a separate issue for it: #142.

Closing this one because it's just one of many consequences of #142.
