### ISSUE TITLE
Kefir Ecosystem

### ISSUE THREAD

**Issue by ivan-kleshnin** [kefirjs/kefir#272]
Hi guys! Dunno where to write this, so making a new issue:

I've made a set of projects and libraries, based on Kefir, which I use in my own company. 
So I thought maybe they can be useful to someone else. 

#### 1. https://github.com/ivan-kleshnin/kefir.db

Extensible reactive states. Docs will be added very soon.

#### 2. https://github.com/ivan-kleshnin/unredux

Apps built on Kefir, Kefir.db with CycleJS-like architecture (no frameworks, lean code).
Examples span from the TODO-app to GraphQL/Falcor alternative (declarative data fetching!).
2 or 3 libraries can be extracted from here.

*I'm sorry about this immodest self-promotion but any PR help (tweet, etc.) will be greatly appreciated ;)* 

And pls. share your projects. I really like how Kefir performs in practice. RxJS, for example, is much more buggy and unstable library, despite what you might expect! (Gonna write an article comparing both soon)

**Comment by mAAdhaTTah** [comment]
I've been working on [brookjs](https://github.com/valtech-nyc/brookjs), which originally was going to have a standalone view layer but is now migrating to be a React extension that will allow you to embed Observables in both JSX & event callbacks. That's still in progress, so there are no docs for it yet; the docs reflect the old view layer.

You may also be interested in [calmm-js](https://github.com/calmm-js/), which looks like they're doing some similar things as what you're doing with kefir.db. I borrowed the idea from karet for brookjs.

**Comment by hallettj** [comment]
Since we are sharing, I developed [redux-slurp](https://github.com/PoodleApp/poodle/tree/master/packages/poodle-core/src/slurp) for one of my projects. (But I have not pulled it into its own package yet.) It provides a HOC that exposes values and errors from an observable or promise as React props. But now I will have to have a look at these other projects!

**Comment by ivan-kleshnin** [comment]
> You may also be interested in calmm-js, which looks like they're doing some similar things as what you're doing with kefir.db. I borrowed the idea from karet for brookjs.

I saw it but honestly I don't like an idea of (direct) mixing Observables and JSX. I think it violates separation of concerns and I find it poorly compatible with my approach to frontend testing.

**Comment by mAAdhaTTah** [comment]
> Honestly I don't like the idea of (direct) mixing Observables and JSX.

Interesting. I love the idea of expressing how your DOM will change as an Observable, and it should make rendering more efficient if you only emit values when they've definitively changed (e.g. what he's going with `kefir.atom`). It feels natural to express changes as Observables everywhere, DOM or otherwise.

I think my main issue is actually with the `kefir.atom` side of things. I'm a heavy Redux user, and the idea of allowing arbitrary state changes in your views bugs me. In `brookjs-silt`, what I want to enable is allowing your events to be declared like this:

```jsx
<button onClick={evt$ => evt$.map(() => clickAction())}>Click me</button>
```

and piping the resulting actions into your Redux store.

**Comment by mAAdhaTTah** [comment]
Since this isn't an issue we can address, I'm going to close for now, but feel free to continue the discussion!

**Comment by ivan-kleshnin** [comment]
> Interesting. I love the idea of expressing how your DOM will change as an Observable, and it should make rendering more efficient if you only emit values when they've definitively changed (e.g. what he's going with kefir.atom). It feels natural to express changes as Observables everywhere, DOM or otherwise.

I meant Calmm-like magic (invisible) injections, when I said I don't like it. If you use streams and React they will be connected to each other somewhere – any argue against that.

> I think my main issue is actually with the kefir.atom side of things. I'm a heavy Redux user, and the idea of allowing arbitrary state changes in your views bugs me. In brookjs-silt, what I want to enable is allowing your events to be declared like this.

I see. I personally don't like Redux actions (as well as Elm). The state of art about... well state composition is relative low, unlike decomposition where you have lenses and plenty of mature toolkit and content around and about them. 

Dispatching functions doesn't have to be arbitrary. You can have a global `transformers` object:

```js
let transformers = {
  t1: function (state) {}    // state -> state
  t2: function (x, state) {} // a -> state -> state
}
```

and dispatch only its functions. So you can test each of them with zero troubles. Anyway, I almost never got bugs in that layer of code, so I'm not very interested in it. It works either way.
